### PR TITLE
Updated the doc strings under functions

### PR DESCRIPTION
**Pull request by sai-krishna-msk**
Usually plots are saved 'png' or 'jpeg', but the functions written is to save as html Specifying that to user might be helpful

__Suggestions__
- Providing the option to save as image file is  kind of useful, (It is just a line of code every where there is plot function, I did not do so because i was not sure if you guys wanted to maintain the interactivity of the plot thus did not provide save as image

### CODE REVIEW

**Comment by sergiocalde94** [comment]
Thank you very much for the PR! Now I'm thinking only in these HTML interactive plots but maybe as you said is useful to add a parameter to choose the file type.

As usually these plots are used in a notebook environment I think it's more useful to have them in HTML. This is the logic behind the current behavior.

For the next version, I'll think about it and if you want to join the conversation feel free 💪

**Comment by sai-krishna-msk** [comment]
> Thank you very much for the PR! Now I'm thinking only in these HTML interactive plots but maybe as you said is useful to add a parameter to choose the file type.
> 
> As usually these plots are used in a notebook environment I think it's more useful to have them in HTML. This is the logic behind the current behavior.
> 
> For the next version, I'll think about it and if you want to join the conversation feel free 💪

yes your right @sergiocalde94 , most people using these packages in notebook, but I've been seeing a thorough shift in the industry towards MLOps(CI/CD) especially after tools like MLFlow, and cases like these(which i am currently using pydrift for) checking training data drift is really important, I think pydrift would be a good fit for these cases as 1) There are'nt many packages in python doing this 2) One's doing these are mostly packages which are heavy(making them undesirable for deployment) , So i was thinking in that direction and thought a PNG/JPEG file maybe more desirable than a HTML file

I would like to hear your take on this

Thank you

**Comment by sergiocalde94** [comment]
So good thoughts about MLOps tools, for that purpose I usually let images out of the equation but maybe it's useful logging those artifacts to MLFLow or whatever. If you want to help me for building the next version we can see it in deep :)

**Comment by sai-krishna-msk** [comment]
> So good thoughts about MLOps tools, for that purpose I usually let images out of the equation but maybe it's useful logging those artifacts to MLFLow or whatever. If you want to help me for building the next version we can see it in deep :)

I don't have much experience building software but sure, Id like to help

**Pull request merged**
